version: '3.7'
volumes:
  mysql_data:
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
  rails:
    image: angtsusiong/mcut-2018-garage
    container_name: mcut-2018-garage
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"
    env_file:
      - .env
    volumes:
      - ./:/home/mcut-2018-garage
    depends_on:
      - db
#  image: mcut_garage
#  container_name: mcut_garage
#  restart: always
#  expose:
#    - "80"
#  volumes:
#    - ./:/home/app
#    - /www/mcut_garage/shared:/www/mcut_garage/shared
#  env_file:
#    - .env
