source 'https://rubygems.org'
ruby '2.5.3'

gem 'rails', '5.2.1'
gem 'rails-i18n'
gem 'jquery-ui-rails'
gem 'jquery-rails'
gem 'tzinfo-data'
gem 'sass-rails'
gem 'compass-rails'
gem 'nprogress-rails', '~> 0.2.0.2'
gem 'jquery-fileupload-rails'
gem 'puma'
gem 'mysql2'
gem 'uglifier'
gem 'webpacker', '~> 3.5'
gem 'devise'
gem 'devise-i18n'
gem 'devise_token_auth'
gem 'jsonapi-resources'
gem 'swagger_ui_engine'
gem 'kaminari'
gem 'kaminari-i18n'
gem 'thor'
gem 'grape'
gem 'grape-swagger'
gem 'enum_help'
gem 'cocoon'
gem 'aasm'
gem 'font-awesome-rails'
gem 'pundit'
gem 'i18n-js'
gem 'rolify'
gem 'ransack'
gem 'seed_dump'
gem 'photoswipe-rails'
gem 'faker'
gem 'paper_trail', '10.0.1'
gem 'simple_form'
gem 'bulk_insert'
gem 'carrierwave', '~> 1.0'
gem 'wysiwyg-rails'
gem 'hashie'
gem 'every8d'
gem 'paperclip'
gem 'news-api'
gem 'rest-client'
gem 'paranoia'
gem 'thredded'
gem 'rack-cors', require: 'rack/cors'
gem 'jquery-slick-rails'

group :development, :test do
  gem 'brakeman', require: false
  gem 'rubocop', require: false
  gem 'sdoc'
  gem 'highline'
  gem 'rails-erd'
  gem 'xray-rails'
  gem 'dotenv-rails'
  gem 'awesome_print'
  gem 'byebug'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'pry-byebug'
  gem 'pry-remote'
  gem 'pry-stack_explorer'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'sshkit-sudo'
  gem 'capistrano'
  gem 'capistrano-wal-e'
  gem 'capistrano-ssh-doctor'
  gem 'capistrano-safe-deploy-to'
  gem 'capistrano-deploy_hooks'
  gem 'larvata_scaffold', git: 'https://github.com/LarvataTW/larvata_scaffold.git'
  gem 'rspec-rails'
  gem 'fabrication'
  gem 'database_cleaner'
  gem 'spring-commands-rspec'
  gem 'guard'
  gem 'guard-livereload'
  gem 'guard-rspec', require: false
  gem 'fuubar'
  gem 'shoulda'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end

group :production do
  gem 'httparty'
  gem 'aws-sdk-s3'
  gem 'rails_12factor'
  gem 'exception_notification'
end

