version: "3.5"

services:

  qps:
    image: registry.larvata.tw/mcut-garage
    environment:
      MAIL_SERVER: $MAIL_SERVER
      MAIL_PORT: $MAIL_PORT
      MAIL_DOMAIN: $MAIL_DOMAIN
      MAIL_ACCOUNT: $MAIL_ACCOUNT
      MAIL_PASSWORD: $MAIL_PASSWORD
      MAIL_RECEIVER: $MAIL_RECEIVER
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      SECRET_KEY_BASE: $SECRET_KEY_BASE
    volumes:
      - log:/home/app/log
      - public_system:/home/app/public/system
    networks:
      - traefik_network
    expose:
      - 80
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:mcut-garage.larvata.tw"
        - "traefik.docker.network=traefik_proxy_network"
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  log:
    driver: local
    driver_opts:
      type: nfs
      o: addr=files.larvata.tw,rw
      device: :/docker_volumes/mcut/garage/log
  public_system:
    driver: local
    driver_opts:
      type: nfs
      o: addr=files.larvata.tw,rw
      device: :/docker_volumes/mcut/garage/public/system

networks:
  traefik_network:
    external: true
    name: traefik_proxy_network
